services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: ./app
      dockerfile: Dockerfile
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    networks:
    - dev-network
    restart: always
    depends_on:
    - api

  aapi:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 3005 -w db.json
    ports:
    - "3005:3005"
    expose:
    - "3005"
    volumes:
    - ./data:/data
    restart: always
    networks:
    - dev-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./api:/app
    restart: always
    networks:
    - dev-network

networks:
  dev-network:
    driver: bridge
