# Build stage
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package

# Deploy stage
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /build/target/*.jar inventory-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "inventory-0.0.1-SNAPSHOT.jar"]
