package com.arti.inventory.security.model;

public enum AppRole {
    USER,
    ADMIN,
    APP_MANAGER,

    APP_MISSION_STAFF,
    APP_MISSION_USER,
    APP_MISSION_MANAGER,
    
    APP_DEVICE_USER,
    APP_PARCAUTO_USER,
    APP_FOURNISSEUR_USER,

    APP_DBOARD_CHIFFRESTRANSPORT,
    APP_DBOARD_COMPTESFINANCES,
    APP_DBOARD_FISCALITE,
    APP_DBOARD_MARCHESPUBLICS,
    APP_DBOARD_PARCAUTO,
    APP_DBOARD_SUIVIDUPERSONNEL
}
